#!/bin/bash
#ssh -i /mnt/HDD1/llaves_google/google_compute_engine -t migue@35.226.107.150 "killall 'ng serve --host'"
#ssh -i /mnt/HDD1/llaves_google/google_compute_engine -t migue@35.226.107.150 "sudo kill -9 $(pidof 'ng serve --host')"
ssh -i /mnt/HDD1/llaves_google/google_compute_engine -t migue@35.238.9.25 '/home/migue/detener-proyecto-loteria'